services:
  rinha-lb:
    image: ghcr.io/alan-venv/rinha-service-2026:test
    container_name: rinha-lb
    command: ["./lb"]
    environment:
      - LB_BIND=0.0.0.0:80
      - UPSTREAMS=/sockets/service-1.sock,/sockets/service-2.sock
      - UPSTREAM_CONNECTIONS_PER_WORKER=6
    ports:
      - 9999:80
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    depends_on:
      - rinha-service-1
      - rinha-service-2
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"

  rinha-service-1:
    image: ghcr.io/alan-venv/rinha-service-2026:test
    container_name: rinha-service-1
    environment:
      - SOCKET=/sockets/service-1.sock
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"

  rinha-service-2:
    image: ghcr.io/alan-venv/rinha-service-2026:test
    container_name: rinha-service-2
    environment:
      - SOCKET=/sockets/service-2.sock
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"

volumes:
  sockets:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=16m,mode=1777

networks:
  backend:
    name: rinha-net
    driver: bridge
