FROM rust:1.94-trixie AS build
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main(){}" > src/main.rs
RUN cargo fetch
COPY src ./src
RUN cargo build --release --bin rinha

FROM gcr.io/distroless/cc-debian13
WORKDIR /app
COPY resources/ivf.bin ./resources/
COPY --from=build /app/target/release/rinha .
ENTRYPOINT [ "./rinha" ]
