FROM rust:1.94-trixie AS build
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main(){}" > src/main.rs
RUN cargo fetch
COPY src ./src
ENV RUSTFLAGS="-C target-cpu=haswell -C target-feature=+avx2"
RUN cargo build --release --bin rinha --bin lb

FROM gcr.io/distroless/cc-debian13
WORKDIR /app
COPY resources/*.bin ./resources/
COPY --from=build /app/target/release/rinha .
COPY --from=build /app/target/release/lb .
CMD [ "./rinha" ]
